
const KEY='epalToolkit.v1';
const COLORS=['#6d5dfc','#00a6a6','#f5a623','#e84a5f','#1b9c85','#9b59b6','#3498db','#e67e22','#2ecc71','#ff6b81'];
const defaultState={
 settings:{theme:'light',subject:'Υγιεινή',players:6,impostors:1,lastModule:'home'},
 stats:{rounds:0,quizCorrect:0,quizTotal:0},
 databases:[
  {id:uid(),subject:'Υγιεινή',name:'Υγιεινή - Βασικό Πακέτο',categories:[
    {id:uid(),name:'Ατομική Υγιεινή',words:[w('Πλύσιμο χεριών','Βασικό μέτρο πρόληψης λοιμώξεων.','Πότε πρέπει να πλένουμε τα χέρια;'),w('Στοματική υγιεινή','Φροντίδα δοντιών και ούλων.','Πόσες φορές τη μέρα συνιστάται βούρτσισμα;'),w('Απολύμανση','Μείωση ή καταστροφή μικροοργανισμών.','Πού διαφέρει από την αποστείρωση;')]},
    {id:uid(),name:'Λοιμώξεις',words:[w('Μικρόβιο','Μικροοργανισμός που μπορεί να προκαλέσει νόσο.','Δώσε ένα παράδειγμα μικροβίου.'),w('Μετάδοση','Τρόπος διασποράς παθογόνων.','Πώς μειώνεται η μετάδοση;'),w('Ανοσία','Ικανότητα άμυνας του οργανισμού.','Τι ρόλο έχουν τα εμβόλια;')]},
    {id:uid(),name:'Διατροφή',words:[w('Πρωτεΐνες','Θρεπτικά συστατικά για ανάπτυξη και επιδιόρθωση.','Ποιες τροφές έχουν πρωτεΐνη;'),w('Υδατάνθρακες','Κύρια πηγή ενέργειας.','Πότε προτιμούμε σύνθετους υδατάνθρακες;'),w('Βιταμίνες','Απαραίτητες οργανικές ενώσεις σε μικρές ποσότητες.','Τι μπορεί να προκαλέσει έλλειψη βιταμινών;')]}
  ]},
  {id:uid(),subject:'Ανατομία',name:'Ανατομία - Βασικό Πακέτο',categories:[
    {id:uid(),name:'Όργανα',words:[w('Καρδιά','Μυώδες όργανο που αντλεί αίμα.','Σε ποιο σύστημα ανήκει;'),w('Πνεύμονας','Όργανο ανταλλαγής αερίων.','Τι προσλαμβάνει ο οργανισμός με την εισπνοή;'),w('Νεφρός','Όργανο αποβολής άχρηστων ουσιών.','Ποιο υγρό παράγει;')]},
    {id:uid(),name:'Οστά',words:[w('Μηριαίο οστό','Το μακρύτερο οστό του ανθρώπινου σώματος.','Σε ποιο άκρο βρίσκεται;'),w('Κλείδα','Οστό της ωμικής ζώνης.','Με ποια περιοχή συνδέεται;'),w('Στέρνο','Πλατύ οστό στο πρόσθιο θωρακικό τοίχωμα.','Τι προστατεύει ο θώρακας;')]},
    {id:uid(),name:'Συστήματα',words:[w('Κυκλοφορικό','Μεταφέρει αίμα, οξυγόνο και θρεπτικά συστατικά.','Ποιο είναι το κεντρικό του όργανο;'),w('Αναπνευστικό','Επιτρέπει την ανταλλαγή αερίων.','Ποια είναι τα βασικά όργανα;'),w('Πεπτικό','Διασπά και απορροφά θρεπτικά συστατικά.','Πού ξεκινά η πέψη;')]}
  ]}
 ]
};
let state=load(); let route='home'; let game=null; let flash=null; let quiz=null; let wheelRot=0;
function uid(){return Math.random().toString(36).slice(2,10)}
function w(term,hint='',quiz=''){return {id:uid(),term,hint,definition:hint,quiz}}
function clone(o){return JSON.parse(JSON.stringify(o))}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)); if(s&&s.databases)return s}catch(e){} return clone(defaultState)}
function save(){localStorage.setItem(KEY,JSON.stringify(state)); document.getElementById('saveState').textContent='Αποθηκεύτηκε'; setTimeout(()=>document.getElementById('saveState').textContent='Ενεργό',900)}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function setRoute(r){route=r; state.settings.lastModule=r; save(); render()}
function subjectDbs(){return state.databases.filter(d=>d.subject===state.settings.subject)}
function allWords(){return subjectDbs().flatMap(db=>db.categories.flatMap(c=>c.words.map(x=>({...x,category:c.name,database:db.name}))))}
function nav(){const items=[['home','🏠','Αρχική'],['impostor','🎮','Impostor'],['flashcards','🃏','Flashcards'],['quiz','❓','Quiz'],['wheel','🎡','Random Wheel'],['db','📚','Βάσεις'],['settings','⚙️','Ρυθμίσεις']];return items.map(i=>`<button class="${route===i[0]?'active':''}" onclick="setRoute('${i[0]}')"><span>${i[1]}</span>${i[2]}</button>`).join('')}
function shell(title,sub){document.body.classList.toggle('dark',state.settings.theme==='dark');document.getElementById('nav').innerHTML=nav();document.getElementById('pageTitle').textContent=title;document.getElementById('pageSubtitle').textContent=sub;document.getElementById('statsChip').textContent=`${state.databases.length} βάσεις • ${allWords().length} λέξεις`;document.getElementById('subjectChip').textContent=`Μάθημα: ${state.settings.subject}`}
function render(){const v=document.getElementById('view'); if(route==='home'){shell('Αρχική','Επίλεξε μάθημα ή άνοιξε ένα εργαλείο.'); v.innerHTML=home()} if(route==='impostor'){shell('Impostor','Κρυφή λέξη, impostors και καθαρή ροή κάρτας.'); v.innerHTML=impostor()} if(route==='flashcards'){shell('Flashcards','Γρήγορη επανάληψη με όρους και ορισμούς.'); v.innerHTML=flashcards()} if(route==='quiz'){shell('Quiz','Αυτόματο quiz από τις λέξεις της βάσης.'); v.innerHTML=quizView()} if(route==='wheel'){shell('Random Wheel','Τυχαία επιλογή όρου για προφορική επανάληψη.'); v.innerHTML=wheel()} if(route==='db'){shell('Βάσεις Δεδομένων','Δημιουργία, επεξεργασία, εισαγωγή και εξαγωγή lesson packs.'); v.innerHTML=dbView()} if(route==='settings'){shell('Ρυθμίσεις','Προεπιλογές, θέμα και backup.'); v.innerHTML=settingsView()} }
function home(){return `<div class="grid"><div class="card span6 module"><div><div class="icon">🩺</div><h3>Υγιεινή</h3><p>Λέξεις και έννοιες για υγιεινή, λοιμώξεις, διατροφή και πρόληψη.</p></div><button class="btn" onclick="selectSubject('Υγιεινή')">Χρήση Υγιεινής</button></div><div class="card span6 module"><div><div class="icon">🦴</div><h3>Ανατομία</h3><p>Όργανα, οστά, συστήματα και βασική ανατομική ορολογία.</p></div><button class="btn" onclick="selectSubject('Ανατομία')">Χρήση Ανατομίας</button></div>${[['impostor','🎮','Impostor','Το κλασικό παιχνίδι με κρυφή λέξη.'],['flashcards','🃏','Flashcards','Επανάληψη όρων με ορισμούς.'],['quiz','❓','Quiz','Ερωτήσεις πολλαπλής επιλογής.'],['wheel','🎡','Random Wheel','Τυχαίος όρος για συζήτηση.'],['db','📚','Database Manager','Φτιάξε και μοιράσου lesson packs.'],['settings','⚙️','Settings','Theme, backup και PWA πληροφορίες.']].map(m=>`<div class="card span4 module"><div><div class="icon">${m[1]}</div><h3>${m[2]}</h3><p>${m[3]}</p></div><button class="btn secondary" onclick="setRoute('${m[0]}')">Άνοιγμα</button></div>`).join('')}</div>`}
window.selectSubject=s=>{state.settings.subject=s;save();toast('Επιλέχθηκε: '+s);render()}
function impostor(){if(!game)return setupGame();return gameView()}
function setupGame(){return `<div class="grid"><div class="card span6 stack"><h3>Ρυθμίσεις γύρου</h3><label><p class="label">Παίκτες</p><input id="players" type="number" min="3" max="30" value="${state.settings.players}"></label><label><p class="label">Impostors</p><input id="imps" type="number" min="1" max="5" value="${state.settings.impostors}"></label><label><p class="label">Κατηγορία</p><select id="catSel"><option value="all">Όλες οι κατηγορίες</option>${subjectDbs().flatMap(db=>db.categories).map(c=>`<option>${esc(c.name)}</option>`).join('')}</select></label><button class="btn" onclick="startGame()">Έναρξη γύρου</button></div><div class="card span6"><h3>Διαθέσιμες λέξεις</h3><p class="big">${allWords().length}</p><p class="hint">Οι λέξεις αντλούνται από όλες τις βάσεις του μαθήματος <b>${state.settings.subject}</b>.</p></div></div>`}
window.startGame=()=>{let players=+document.getElementById('players').value, imps=+document.getElementById('imps').value; let cat=document.getElementById('catSel').value; let pool=allWords().filter(x=>cat==='all'||x.category===cat); if(players<3||imps>=players||pool.length<1){toast('Έλεγξε παίκτες/impostors/λέξεις.');return} let secret=pool[Math.floor(Math.random()*pool.length)]; let impSet=new Set(); while(impSet.size<imps)impSet.add(Math.floor(Math.random()*players)); game={players,imps,secret,impSet:[...impSet],idx:0,phase:'hidden'}; state.settings.players=players; state.settings.impostors=imps; save(); render()}
function gameView(){let pct=(game.idx/game.players)*100; let isImp=game.impSet.includes(game.idx); let color=COLORS[game.idx%COLORS.length]; let content=''; if(game.phase==='hidden')content=`<div><div class="playerBadge" style="background:${color}">${game.idx+1}</div><h3>Παίκτης ${game.idx+1}</h3><p class="hint">Μόνο ο Παίκτης ${game.idx+1} πρέπει να κοιτάξει.</p><button class="btn" onclick="game.phase='shown';render()">👁️ Εμφάνιση κάρτας</button></div>`; if(game.phase==='shown')content=`<div><div class="playerBadge" style="background:${isImp?'#e84a5f':color}">${isImp?'🕵️':game.idx+1}</div><div class="big">${isImp?'IMPOSTOR':esc(game.secret.term)}</div><p class="hint">${isImp?'Άκου προσεκτικά και προσπάθησε να μαντέψεις.':esc(game.secret.hint||game.secret.definition||'')}</p><button class="btn ok" onclick="game.phase='covered';render()">Το είδα</button></div>`; if(game.phase==='covered')content=`<div><div class="big">✅</div><h3>Η κάρτα αποκρύφθηκε</h3><p class="hint">Παραδώστε τη συσκευή στον επόμενο παίκτη.</p><button class="btn" onclick="nextPlayer()">${game.idx===game.players-1?'Ολοκλήρωση γύρου':'Επόμενος παίκτης'}</button></div>`; if(game.phase==='end')content=`<div><div class="big">🎉</div><h3>Ο γύρος ολοκληρώθηκε!</h3><p class="hint">Μυστική λέξη</p><div class="big">${esc(game.secret.term)}</div><p>🕵️ Impostor: ${game.impSet.map(i=>'Παίκτης '+(i+1)).join(', ')}</p><div class="row" style="justify-content:center"><button class="btn" onclick="game=null;render()">Νέος γύρος</button><button class="btn secondary" onclick="teacherInfo()">📚 Teacher Mode</button></div><div id="teacherInfo"></div></div>`; return `<div class="card span12"><div class="progress"><div class="bar" style="width:${game.phase==='end'?100:pct}%"></div></div><br><div class="gameCard">${content}</div></div>`}
window.nextPlayer=()=>{if(game.idx===game.players-1){game.phase='end';state.stats.rounds++;save()}else{game.idx++;game.phase='hidden'}render()}
window.teacherInfo=()=>{const el=document.getElementById('teacherInfo'); if(el)el.innerHTML=`<div class="card" style="margin-top:16px;text-align:left"><h3>📚 Εκπαιδευτικές πληροφορίες</h3><p><b>Όρος:</b> ${esc(game.secret.term)}</p><p><b>Ορισμός:</b> ${esc(game.secret.definition||game.secret.hint||'Δεν υπάρχει ορισμός.')}</p><p><b>Κατηγορία:</b> ${esc(game.secret.category)}</p><p><b>Ερώτηση:</b> ${esc(game.secret.quiz||'Ζητήστε από τους μαθητές να εξηγήσουν τον όρο με δικά τους λόγια.')}</p></div>`}
function flashcards(){let words=allWords(); if(!flash||!words.find(w=>w.id===flash.id)) flash={i:0,show:false,id:words[0]?.id}; if(!words.length)return emptyWords(); let item=words[flash.i%words.length];return `<div class="card"><div class="row between"><button class="btn secondary" onclick="flash.i=(flash.i-1+${words.length})%${words.length};flash.show=false;render()">← Προηγούμενη</button><span class="pill">${flash.i+1}/${words.length}</span><button class="btn secondary" onclick="flash.i=(flash.i+1)%${words.length};flash.show=false;render()">Επόμενη →</button></div><br><div class="gameCard" onclick="flash.show=!flash.show;render()"><div><p class="pill">${esc(item.category)}</p><div class="big">${esc(item.term)}</div><p class="hint">${flash.show?esc(item.definition||item.hint||'Δεν υπάρχει ορισμός.'): 'Πάτησε την κάρτα για ορισμό.'}</p></div></div></div>`}
function quizView(){let words=allWords(); if(words.length<4)return `<div class="card"><h3>Χρειάζονται τουλάχιστον 4 λέξεις</h3><p class="hint">Πρόσθεσε περισσότερες λέξεις στις βάσεις.</p></div>`; if(!quiz) newQuiz(); let q=quiz; return `<div class="card"><p class="pill">Score: ${state.stats.quizCorrect}/${state.stats.quizTotal}</p><h3>Τι περιγράφει ο ορισμός;</h3><p class="hint">${esc(q.def)}</p><div class="stack" style="margin-top:18px">${q.choices.map(c=>`<button class="quizChoice ${q.answered?(c===q.answer?'correct':(c===q.pick?'wrong':'')):''}" onclick="answerQuiz('${escAttr(c)}')">${esc(c)}</button>`).join('')}</div>${q.answered?'<br><button class="btn" onclick="newQuiz();render()">Επόμενη ερώτηση</button>':''}</div>`}
function newQuiz(){let words=allWords().filter(x=>x.definition||x.hint);let ans=words[Math.floor(Math.random()*words.length)];let choices=[ans.term]; while(choices.length<4){let t=words[Math.floor(Math.random()*words.length)].term;if(!choices.includes(t))choices.push(t)} quiz={def:ans.definition||ans.hint,answer:ans.term,choices:shuffle(choices),answered:false,pick:null}}
window.answerQuiz=c=>{if(quiz.answered)return; quiz.answered=true; quiz.pick=c; state.stats.quizTotal++; if(c===quiz.answer)state.stats.quizCorrect++; save(); render()}
window.newQuiz=newQuiz;
function wheel(){let words=allWords();return `<div class="card"><div class="wheel" id="wheel" style="transform:rotate(${wheelRot}deg)"><div class="wheelInner" id="wheelText">${words.length?'Πάτησε Spin':'Δεν υπάρχουν λέξεις'}</div></div><br><div class="row" style="justify-content:center"><button class="btn" onclick="spinWheel()">🎡 Spin</button></div></div>`}
window.spinWheel=()=>{let words=allWords();if(!words.length)return;let item=words[Math.floor(Math.random()*words.length)];wheelRot+=720+Math.floor(Math.random()*360);document.getElementById('wheel').style.transform=`rotate(${wheelRot}deg)`;setTimeout(()=>{document.getElementById('wheelText').innerHTML=`${esc(item.term)}<br><span class="small">${esc(item.category)}</span>`},900)}
function dbView(){return `<div class="grid"><div class="card span12 row"><button class="btn" onclick="addDb()">➕ Νέα βάση</button><button class="btn secondary" onclick="document.getElementById('importFile').click()">📂 Εισαγωγή</button><button class="btn secondary" onclick="exportAll()">💾 Export όλα</button></div>${state.databases.map(db=>`<div class="card span6"><div class="row between"><div><h3>${esc(db.name)}</h3><p class="small">${esc(db.subject)} • ${db.categories.length} κατηγορίες • ${db.categories.reduce((a,c)=>a+c.words.length,0)} λέξεις</p></div><span class="pill">${db.subject==='Υγιεινή'?'🩺':'🦴'}</span></div><div class="row"><button class="btn secondary" onclick="editDb('${db.id}')">✏️ Επεξεργασία</button><button class="btn secondary" onclick="exportDb('${db.id}')">Export</button><button class="btn danger" onclick="delDb('${db.id}')">Διαγραφή</button></div></div>`).join('')}</div><div id="editor"></div>`}
window.addDb=()=>{let name=prompt('Όνομα νέας βάσης:','Νέα βάση');if(!name)return;state.databases.push({id:uid(),subject:state.settings.subject,name,categories:[]});save();render()}
window.delDb=id=>{if(confirm('Διαγραφή βάσης;')){state.databases=state.databases.filter(d=>d.id!==id);save();render()}}
window.editDb=id=>{let db=state.databases.find(d=>d.id===id);let name=prompt('Όνομα βάσης:',db.name); if(name!==null)db.name=name; let cat=prompt('Προσθήκη κατηγορίας (άφησε κενό αν δεν θέλεις):',''); if(cat)db.categories.push({id:uid(),name:cat,words:[]}); let cats=db.categories.map((c,i)=>`${i+1}. ${c.name}`).join('\n'); let pick=prompt('Σε ποια κατηγορία να προσθέσω λέξη;\n'+cats+'\n(γράψε αριθμό ή άφησε κενό)', ''); if(pick){let c=db.categories[+pick-1]; if(c){let term=prompt('Λέξη/όρος:',''); if(term){let hint=prompt('Hint / ορισμός:',''); let qq=prompt('Ερώτηση Teacher Mode:',''); c.words.push(w(term,hint,qq));}}} save();render()}
function pack(db){return {app:'Teacher Toolkit ΕΠΑΛ',version:1,exportedAt:new Date().toISOString(),databases:Array.isArray(db)?db:[db]}}
window.exportDb=id=>download(JSON.stringify(pack(state.databases.find(d=>d.id===id)),null,2),'lesson-pack.epack')
window.exportAll=()=>download(JSON.stringify(pack(state.databases),null,2),'epal-toolkit-backup.epack')
document.getElementById('importFile').addEventListener('change',e=>{let f=e.target.files[0]; if(!f)return; let r=new FileReader(); r.onload=()=>{try{let p=JSON.parse(r.result); let dbs=p.databases||[p]; dbs.forEach(db=>{db.id=uid(); db.categories=(db.categories||[]).map(c=>({id:uid(),name:c.name,words:(c.words||[]).map(x=>typeof x==='string'?w(x):{id:uid(),term:x.term||x.word||'',hint:x.hint||'',definition:x.definition||x.hint||'',quiz:x.quiz||''})})); state.databases.push(db)});save();toast('Έγινε εισαγωγή.');render()}catch(err){toast('Μη έγκυρο JSON/epack.')}};r.readAsText(f);e.target.value=''})
function settingsView(){return `<div class="grid"><div class="card span6 stack"><h3>Ρυθμίσεις</h3><label><p class="label">Θέμα</p><select onchange="state.settings.theme=this.value;save();render()"><option ${state.settings.theme==='light'?'selected':''} value="light">Light</option><option ${state.settings.theme==='dark'?'selected':''} value="dark">Dark</option></select></label><label><p class="label">Προεπιλεγμένο μάθημα</p><select onchange="state.settings.subject=this.value;save();render()"><option ${state.settings.subject==='Υγιεινή'?'selected':''}>Υγιεινή</option><option ${state.settings.subject==='Ανατομία'?'selected':''}>Ανατομία</option></select></label><button class="btn secondary" onclick="exportAll()">Κατέβασμα backup</button><button class="btn danger" onclick="resetApp()">Reset εφαρμογής</button></div><div class="card span6"><h3>PWA / GitHub Pages</h3><p class="hint" style="text-align:left">Αν ανέβει ως <b>index.html</b> μαζί με <b>manifest.json</b> και <b>sw.js</b>, οι χρήστες μπορούν να το εγκαταστήσουν σαν app. Τα δεδομένα αποθηκεύονται τοπικά στο browser κάθε συσκευής, όχι στο GitHub.</p><p class="small">Για μεταφορά σε άλλο υπολογιστή: Export → αρχείο .epack → Import στη νέα συσκευή.</p></div></div>`}
window.resetApp=()=>{if(confirm('Reset όλων των τοπικών δεδομένων; Κάνε πρώτα export αν χρειάζεται.')){localStorage.removeItem(KEY);state=clone(defaultState);game=flash=quiz=null;render()}}
function emptyWords(){return `<div class="card"><h3>Δεν υπάρχουν λέξεις για ${state.settings.subject}</h3><p class="hint">Πήγαινε στις Βάσεις και πρόσθεσε ή εισήγαγε lesson pack.</p></div>`}
function download(txt,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function shuffle(a){return a.sort(()=>Math.random()-.5)} function esc(s=''){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))} function escAttr(s=''){return esc(s).replace(/'/g,'&#39;').replace(/"/g,'&quot;')}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
render();
